"""setup_elevenlabs_agent.py
One-shot script to create the ElevenLabs Conversational AI agent for SO-101 peanut handoff.

Usage:
    python setup_elevenlabs_agent.py --api-key sk_xxxxxxxxxxxx

This will:
  1. Create the agent via the ElevenLabs REST API with the exact system prompt + client tools
  2. Print the Agent ID
  3. Write a config.py with your credentials for use by voice_robot_agent.py
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.request
import urllib.error

# ── System Prompt ──────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are the voice interface for an SO-101 robot.

You recognize requests for one supported task:

Task ID: peanut_handoff
Meaning: Pick up one peanut and present it in front of the person's mouth.

When the user asks to feed, bring, hand over, or present a peanut:
1. Ask: "Should I start the peanut handoff?"
2. Wait for an explicit yes.
3. Call the run_robot_task client tool with:
   task_id = "peanut_handoff"
4. Never generate robot joint positions.
5. Never generate or modify the policy instruction.
6. Never call the tool for unsupported objects or tasks.
7. If the user says stop, cancel, emergency, or abort, immediately call stop_robot_task.
8. Report the tool result clearly.

The local robot controller performs an additional physical confirmation before movement. Do not claim that the task succeeded unless the tool reports success."""

# ── Client Tool Schemas ────────────────────────────────────────────────────────
CLIENT_TOOLS = [
    {
        "type": "client",
        "name": "run_robot_task",
        "description": (
            "Execute an approved SO-101 robot task. Only call with task_id='peanut_handoff'. "
            "The local controller maps this task_id to the canonical policy instruction internally."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string",
                    "description": "The approved task identifier. Must be 'peanut_handoff'.",
                }
            },
            "required": ["task_id"],
        },
        "expects_response": True,
    },
    {
        "type": "client",
        "name": "stop_robot_task",
        "description": (
            "Immediately halt and abort any active SO-101 robot movement. "
            "Call this when the user says stop, cancel, abort, or emergency."
        ),
        "parameters": {
            "type": "object",
            "properties": {},
            "required": [],
        },
        "expects_response": True,
    },
]

# ── Agent Config ───────────────────────────────────────────────────────────────
AGENT_CONFIG = {
    "name": "SO-101 Peanut Handoff Voice Interface",
    "conversation_config": {
        "agent": {
            "prompt": {
                "prompt": SYSTEM_PROMPT,
                "tools": CLIENT_TOOLS,
            },
            "first_message": "Hello! I'm the SO-101 robot assistant. Ask me to hand you a peanut.",
            "language": "en",
        },
        "tts": {
            "voice_id": "cgSgspJ2msm6clMCkdW9",  # Default 'Jessica' - clear, friendly voice
        },
        "turn": {
            "mode": "turn",
            "turn_timeout": 7,
        },
    },
    "platform_settings": {
        "auth": {"enable_auth": True},
    },
}


def create_agent(api_key: str) -> str:
    """Create the ElevenLabs agent and return the agent_id."""
    url = "https://api.elevenlabs.io/v1/convai/agents/create"
    body = json.dumps(AGENT_CONFIG).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
            return data["agent_id"]
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"ERROR {e.code}: {body}", file=sys.stderr)
        sys.exit(1)


def write_config(api_key: str, agent_id: str):
    """Write config.py next to voice_robot_agent.py."""
    import pathlib
    config_path = pathlib.Path(__file__).parent / "config.py"
    config_path.write_text(
        f'# Auto-generated by setup_elevenlabs_agent.py — DO NOT commit this file\n'
        f'ELEVENLABS_API_KEY = "{api_key}"\n'
        f'AGENT_ID = "{agent_id}"\n'
    )
    print(f"\n✓ Credentials written to {config_path}")
    print("  (This file is gitignored — it will not be pushed to GitHub)\n")


def ensure_gitignore():
    """Make sure config.py is gitignored."""
    import pathlib
    gi = pathlib.Path(__file__).parent.parent / ".gitignore"
    entry = "voice-agent/config.py\n"
    if gi.exists():
        content = gi.read_text()
        if "voice-agent/config.py" not in content:
            gi.write_text(content + entry)
            print("✓ Added voice-agent/config.py to .gitignore")
    else:
        gi.write_text(entry)
        print("✓ Created .gitignore with voice-agent/config.py")


def main():
    parser = argparse.ArgumentParser(description="Create ElevenLabs agent for SO-101")
    parser.add_argument("--api-key", required=True, help="Your ElevenLabs API key (sk_...)")
    args = parser.parse_args()

    print("Creating ElevenLabs Conversational AI agent...")
    agent_id = create_agent(args.api_key)

    print(f"\n{'='*65}")
    print(f"  ✓ Agent Created Successfully!")
    print(f"  Agent ID:  {agent_id}")
    print(f"  Name:      SO-101 Peanut Handoff Voice Interface")
    print(f"{'='*65}")

    write_config(args.api_key, agent_id)
    ensure_gitignore()

    print("Next steps:")
    print("  1. Test voice (dry-run):   python voice_robot_agent.py --dry-run")
    print("  2. Hardware deployment:    python voice_robot_agent.py --camera=/dev/video4 --enable-motion")
    print()


if __name__ == "__main__":
    main()

